-- ============================================================================
-- MONEYA LATAM - SETUP UNICO (SQL Editor de Supabase)
-- Ejecutar UNA sola vez sobre un proyecto NUEVO, en un solo pegado.
-- Contenido = migraciones 0001..0005 en orden (schema + RLS + seeds + triggers).
-- Fuente de verdad: supabase/migrations/0001..0005.sql (mantener paridad).
-- ============================================================================
-- =============================================================

-- Migracion 0001 : 0001_initial_schema.sql

-- =============================================================

-- ============================================================================
-- MONEYA LATAM — V1 schema (PRD V2, secciones 12 y 20)
-- Alcance: MVP Chile + Perú. Solo tablas que V1 usa; nada "por si acaso".
-- Reglas no negociables aplicadas:
--   3. RLS activado tabla por tabla desde esta primera migración.
--   5. `indicators` solo acepta las 4 métricas Global Findex 2025 (enum).
--   Métrica norte (sección 18): tabla `events` para telemetría, sin valores
--      financieros en `properties` (regla 7, se aplica en la capa de app).
-- ============================================================================

begin;

-- ---------------------------------------------------------------------------
-- Tipos
-- ---------------------------------------------------------------------------
create type public.age_bucket as enum ('18_61', '62_plus');
create type public.employment_status as enum ('dependiente', 'independiente', 'mixto', 'estudiante', 'sin_empleo', 'otro');
create type public.liability_type as enum ('tarjeta', 'prestamo', 'hipoteca', 'vehiculo', 'otro');
create type public.scenario_type as enum ('ingresos_menos', 'gastos_mas', 'perdida_ingreso', 'emergencia', 'personalizado');
create type public.mission_status as enum ('no_iniciada', 'en_curso', 'completada');
create type public.lesson_topic as enum ('room_for_error', 'never_enough', 'status_consumption', 'invisible_wealth', 'luck_risk');
create type public.event_name as enum ('onboarding_completed', 'test_completed', 'profile_saved', 'simulation_created', 'mission_completed');

-- ---------------------------------------------------------------------------
-- Tablas de referencia (lectura para usuarios autenticados; escritura solo
-- vía service_role: sin policies de escritura).
-- ---------------------------------------------------------------------------
create table public.countries (
    id            smallint generated by default as identity primary key,
    code          text unique not null check (code in ('CL', 'PE')),
    name          text not null,
    currency_code text not null,
    locale        text not null
);

-- Regla 5 del PRD: la tabla `indicators` solo acepta las 4 métricas de Global
-- Findex 2025 en V1. Cualquier indicador nuevo requiere migración + ficha en
-- `indicator_sources`.
create type public.indicator_key as enum (
    'account_ownership',      -- % adultos con cuenta financiera (account.t.d / FX.OWN.TOTL.ZS)
    'saved_formally_last_year', -- % que ahorró formalmente en el último año (fin17a.17a1.d)
    'formal_credit_access',   -- % con acceso a crédito formal (fin22a.22a1.22g.d)
    'emergency_funds'         -- % que podría acceder a dinero extra en una emergencia (fin44)
);

create table public.indicator_sources (
    id           uuid primary key default gen_random_uuid(),
    source_key   text unique not null,
    name         text not null,
    institution  text not null,
    edition      text not null,
    data_year    smallint not null,
    methodology  text not null,
    url          text not null,
    accessed_at  date not null default current_date,
    notes        text
);

create table public.indicators (
    id            uuid primary key default gen_random_uuid(),
    indicator_key public.indicator_key not null,
    country_id    smallint not null references public.countries (id),
    source_id     uuid not null references public.indicator_sources (id),
    value         numeric(5,2) check (value between 0 and 100),
    unit          text not null default '%',
    year          smallint not null,
    fnd_code      text,
    unique (indicator_key, country_id, source_id)
);

create table public.missions (
    id               uuid primary key default gen_random_uuid(),
    slug             text unique not null,
    title            text not null,
    description      text not null,
    sort_order       smallint not null,
    required_actions jsonb not null default '[]'::jsonb
);

create table public.lessons (
    id              uuid primary key default gen_random_uuid(),
    slug            text unique not null,
    title           text not null,
    summary         text not null,
    body            text not null,
    topic           public.lesson_topic not null,
    reading_minutes smallint not null default 3 check (reading_minutes > 0),
    published       boolean not null default false,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Tablas del usuario
-- ---------------------------------------------------------------------------
create table public.profiles (
    id                uuid primary key references auth.users (id) on delete cascade,
    country_id        smallint not null references public.countries (id),
    -- El tramo de edad es requisito del scoring CFPB (18–61 vs 62+), sección 9 del PRD.
    age_bucket        public.age_bucket not null,
    employment_status public.employment_status not null,
    created_at        timestamptz not null default now(),
    updated_at        timestamptz not null default now()
);

-- Snapshot mensual. Corrección PRD: requiere saldo de liquidez (para "meses de
-- cobertura") e ingreso desglosado por fuente (para "concentración de ingreso").
create table public.financial_inputs (
    id                   uuid primary key default gen_random_uuid(),
    user_id              uuid not null references auth.users (id) on delete cascade,
    snapshot_month       date not null,
    income_dependiente   numeric(14,2) not null default 0 check (income_dependiente >= 0),
    income_independiente numeric(14,2) not null default 0 check (income_independiente >= 0),
    income_otros         numeric(14,2) not null default 0 check (income_otros >= 0),
    expenses_essential   numeric(14,2) not null default 0 check (expenses_essential >= 0),
    expenses_nonessential numeric(14,2) not null default 0 check (expenses_nonessential >= 0),
    liquid_balance       numeric(14,2) not null default 0 check (liquid_balance >= 0),
    created_at           timestamptz not null default now(),
    updated_at           timestamptz not null default now(),
    unique (user_id, snapshot_month),
    check (snapshot_month = (date_trunc('month', snapshot_month))::date)
);

create table public.liabilities (
    id             uuid primary key default gen_random_uuid(),
    user_id        uuid not null references auth.users (id) on delete cascade,
    name           text not null,
    type           public.liability_type not null,
    balance        numeric(14,2) not null check (balance >= 0),
    monthly_payment numeric(14,2) not null check (monthly_payment >= 0),
    annual_rate    numeric(6,2) not null default 0 check (annual_rate >= 0),
    created_at     timestamptz not null default now(),
    updated_at     timestamptz not null default now()
);

-- Respuestas crudas del cuestionario CFPB adaptado. Regla de validez: la escala
-- requiere que TODOS los ítems estén respondidos y que no se altere la redacción.
create table public.wellbeing_answers (
    id                 uuid primary key default gen_random_uuid(),
    user_id            uuid not null references auth.users (id) on delete cascade,
    answered_at        timestamptz not null default now(),
    items              jsonb not null,
    all_items_answered boolean not null default false,
    check (jsonb_typeof(items) = 'array')
);

-- Score ÚNICO validado CFPB (0–100, método IRT) + desglose DESCRIPTIVO de las
-- 4 dimensiones de la escala. Las dimensiones NO son scores psicométricos.
create table public.wellbeing_results (
    id                 uuid primary key default gen_random_uuid(),
    user_id            uuid not null references auth.users (id) on delete cascade,
    answers_id         uuid not null references public.wellbeing_answers (id) on delete cascade,
    score              smallint not null check (score between 0 and 100),
    dimension_control  smallint not null check (dimension_control between 0 and 100),
    dimension_shock    smallint not null check (dimension_shock between 0 and 100),
    dimension_goals    smallint not null check (dimension_goals between 0 and 100),
    dimension_freedom  smallint not null check (dimension_freedom between 0 and 100),
    note               text not null default 'Desglose descriptivo derivado de los ítems CFPB; no constituye un score psicométrico por dimensión.',
    created_at         timestamptz not null default now(),
    unique (answers_id)
);

-- "Qué pasa si": `params` guarda los inputs usados y `result` el cálculo
-- determinístico. Permite mostrar fórmula e inputs (regla 2 del PRD). Nunca
-- se calcula con IA.
create table public.simulations (
    id            uuid primary key default gen_random_uuid(),
    user_id       uuid not null references auth.users (id) on delete cascade,
    name          text not null,
    scenario_type public.scenario_type not null,
    params        jsonb not null,
    result        jsonb not null,
    created_at    timestamptz not null default now()
);

create table public.mission_progress (
    id          uuid primary key default gen_random_uuid(),
    user_id     uuid not null references auth.users (id) on delete cascade,
    mission_id  uuid not null references public.missions (id) on delete cascade,
    status      public.mission_status not null default 'no_iniciada',
    actions_done jsonb not null default '[]'::jsonb,
    completed_at timestamptz,
    updated_at  timestamptz not null default now(),
    unique (user_id, mission_id)
);

-- Telemetría (métrica norte, sección 18 PRD). REGLA 7: `properties` jamás
-- contiene valores financieros del usuario.
create table public.events (
    id          bigint generated by default as identity primary key,
    user_id     uuid references auth.users (id) on delete set null,
    event_name  public.event_name not null,
    properties  jsonb not null default '{}'::jsonb,
    created_at  timestamptz not null default now()
);

-- Toda modificación de datos financieros del usuario (PRD sección 12).
create table public.audit_logs (
    id          bigint generated by default as identity primary key,
    user_id     uuid not null references auth.users (id) on delete cascade,
    table_name  text not null,
    record_id   uuid not null,
    action      text not null check (action in ('INSERT', 'UPDATE', 'DELETE')),
    changed_at  timestamptz not null default now(),
    data        jsonb not null
);

-- ---------------------------------------------------------------------------
-- Triggers de apoyo
-- ---------------------------------------------------------------------------
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at := now();
    return new;
end;
$$;

create trigger trg_profiles_updated_at
    before update on public.profiles
    for each row execute function public.touch_updated_at();
create trigger trg_financial_inputs_updated_at
    before update on public.financial_inputs
    for each row execute function public.touch_updated_at();
create trigger trg_liabilities_updated_at
    before update on public.liabilities
    for each row execute function public.touch_updated_at();
create trigger trg_mission_progress_updated_at
    before update on public.mission_progress
    for each row execute function public.touch_updated_at();
create trigger trg_lessons_updated_at
    before update on public.lessons
    for each row execute function public.touch_updated_at();

-- Auditoría (security definer: el usuario no puede insertar logs falsos).
create or replace function public.audit_financial_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    acting_user uuid := auth.uid();
    record_id  uuid;
    snapshot   jsonb;
begin
    -- Sin contexto de usuario autenticado no se registra log (evita user_id inválidos).
    if acting_user is null then
        return coalesce(new, old);
    end if;
    record_id := coalesce(new.id, old.id);
    if tg_op = 'DELETE' then
        snapshot := to_jsonb(old);
    else
        snapshot := to_jsonb(new);
    end if;
    insert into public.audit_logs (user_id, table_name, record_id, action, data)
    values (acting_user, tg_table_name, record_id, tg_op::text, snapshot);
    return coalesce(new, old);
end;
$$;

create trigger trg_financial_inputs_audit
    after insert or update or delete on public.financial_inputs
    for each row execute function public.audit_financial_change();
create trigger trg_liabilities_audit
    after insert or update or delete on public.liabilities
    for each row execute function public.audit_financial_change();
create trigger trg_simulations_audit
    after insert or update or delete on public.simulations
    for each row execute function public.audit_financial_change();

-- ---------------------------------------------------------------------------
-- Row-Level Security (regla 3: tabla por tabla, desde la primera migración)
-- ---------------------------------------------------------------------------

-- Referencia: lectura para autenticados, escritura solo service_role.
alter table public.countries enable row level security;
alter table public.indicator_sources enable row level security;
alter table public.indicators enable row level security;
alter table public.missions enable row level security;
alter table public.lessons enable row level security;

create policy "countries_read_authenticated" on public.countries
    for select to authenticated using (true);
create policy "indicator_sources_read_authenticated" on public.indicator_sources
    for select to authenticated using (true);
create policy "indicators_read_authenticated" on public.indicators
    for select to authenticated using (true);
create policy "missions_read_authenticated" on public.missions
    for select to authenticated using (true);
create policy "lessons_read_authenticated" on public.lessons
    for select to authenticated using (true);

-- Datos del usuario: cada usuario solo ve/modifica sus propias filas.
alter table public.profiles enable row level security;
create policy "profiles_select_own" on public.profiles
    for select using (id = auth.uid());
create policy "profiles_insert_own" on public.profiles
    for insert with check (id = auth.uid());
create policy "profiles_update_own" on public.profiles
    for update using (id = auth.uid()) with check (id = auth.uid());

alter table public.financial_inputs enable row level security;
create policy "financial_inputs_select_own" on public.financial_inputs
    for select using (user_id = auth.uid());
create policy "financial_inputs_insert_own" on public.financial_inputs
    for insert with check (user_id = auth.uid());
create policy "financial_inputs_update_own" on public.financial_inputs
    for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "financial_inputs_delete_own" on public.financial_inputs
    for delete using (user_id = auth.uid());

alter table public.liabilities enable row level security;
create policy "liabilities_select_own" on public.liabilities
    for select using (user_id = auth.uid());
create policy "liabilities_insert_own" on public.liabilities
    for insert with check (user_id = auth.uid());
create policy "liabilities_update_own" on public.liabilities
    for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "liabilities_delete_own" on public.liabilities
    for delete using (user_id = auth.uid());

alter table public.wellbeing_answers enable row level security;
create policy "wellbeing_answers_select_own" on public.wellbeing_answers
    for select using (user_id = auth.uid());
create policy "wellbeing_answers_insert_own" on public.wellbeing_answers
    for insert with check (user_id = auth.uid());
create policy "wellbeing_answers_delete_own" on public.wellbeing_answers
    for delete using (user_id = auth.uid());

alter table public.wellbeing_results enable row level security;
create policy "wellbeing_results_select_own" on public.wellbeing_results
    for select using (user_id = auth.uid());
create policy "wellbeing_results_insert_own" on public.wellbeing_results
    for insert with check (user_id = auth.uid());
create policy "wellbeing_results_delete_own" on public.wellbeing_results
    for delete using (user_id = auth.uid());

alter table public.simulations enable row level security;
create policy "simulations_select_own" on public.simulations
    for select using (user_id = auth.uid());
create policy "simulations_insert_own" on public.simulations
    for insert with check (user_id = auth.uid());
create policy "simulations_update_own" on public.simulations
    for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "simulations_delete_own" on public.simulations
    for delete using (user_id = auth.uid());

alter table public.mission_progress enable row level security;
create policy "mission_progress_select_own" on public.mission_progress
    for select using (user_id = auth.uid());
create policy "mission_progress_insert_own" on public.mission_progress
    for insert with check (user_id = auth.uid());
create policy "mission_progress_update_own" on public.mission_progress
    for update using (user_id = auth.uid()) with check (user_id = auth.uid());

alter table public.events enable row level security;
create policy "events_insert_own" on public.events
    for insert with check (user_id = auth.uid());
create policy "events_select_own" on public.events
    for select using (user_id = auth.uid());

-- Sin policies de insert/update/delete: los logs solo los escribe el trigger
-- security definer. El usuario puede leer y, para borrado (derecho al olvido),
-- eliminar sus propias filas.
alter table public.audit_logs enable row level security;
create policy "audit_logs_select_own" on public.audit_logs
    for select using (user_id = auth.uid());
create policy "audit_logs_delete_own" on public.audit_logs
    for delete using (user_id = auth.uid());

-- ---------------------------------------------------------------------------
-- Índices de uso frecuente
-- ---------------------------------------------------------------------------
create index idx_financial_inputs_user_month on public.financial_inputs (user_id, snapshot_month);
create index idx_liabilities_user on public.liabilities (user_id);
create index idx_wellbeing_results_user on public.wellbeing_results (user_id);
create index idx_simulations_user on public.simulations (user_id);
create index idx_mission_progress_user on public.mission_progress (user_id);
create index idx_events_user_created on public.events (user_id, created_at);
create index idx_audit_logs_user on public.audit_logs (user_id, changed_at);
create index idx_indicators_country_key on public.indicators (country_id, indicator_key);

commit;

-- =============================================================

-- Migracion 0002 : 0002_seed_indicators.sql

-- =============================================================

-- ============================================================================
-- MONEYA LATAM — Seed V1 (PRD secciones 10 y 17)
--   * Países (Chile, Perú)
--   * 1 ficha de fuente (Global Findex 2025) + 8 registros de indicadores
--   * Las 5 misiones del MVP
-- Regla del PRD: NO se inventan cifras. Valores VERIFICADOS del dataset oficial
-- Global Findex 2025 (ronda 2024, World Bank, CC BY-4.0):
--   * Chile  cuenta 85,1%
--   * Perú   cuenta 59,3% · ahorro formal 31,4% · crédito formal 20,8%
-- La ronda 2024 NO publica ahorro/crédito/digital para Chile (dash en el dataset
-- oficial); esos indicadores quedan en NULL hasta verificar desde el CSV oficial
-- (worldbank.org/en/publication/globalfindex/download-data). Nunca se estiman.
-- ============================================================================

begin;

-- ---------------------------------------------------------------------------
-- Países
-- ---------------------------------------------------------------------------
insert into public.countries (code, name, currency_code, locale) values
    ('CL', 'Chile', 'CLP', 'es-CL'),
    ('PE', 'Perú',  'PEN', 'es-PE');

-- ---------------------------------------------------------------------------
-- Ficha de fuente (sección 10 del PRD: cada indicador con ficha completa)
-- ---------------------------------------------------------------------------
insert into public.indicator_sources (
    source_key, name, institution, edition, data_year, methodology, url, accessed_at, notes
) values (
    'global-findex-2025',
    'Global Findex Database 2025',
    'Banco Mundial (World Bank)',
    '2025 — 5ª edición',
    2024,
    'Encuesta nacional representativa de demanda (población 15+); ~145.000–148.000 adultos en 141 economías; trabajo de campo 2024. Publicado jul 2025. Uso CC BY-4.0. Cita recomendada: Klapper, L., Singer, D., Starita, L. y Norris, A. 2025. The Global Findex Database 2025: Connectivity and Financial Inclusion in the Digital Economy. World Bank, Washington, DC.',
    'https://www.worldbank.org/en/publication/globalfindex',
    '2026-09-24',
    'Valores por país descargables (Excel/CSV/Stata/Databank): https://www.worldbank.org/en/publication/globalfindex/download-data. Verificados (ronda 2024): Chile cuenta 85,1%; Perú cuenta 59,3%, ahorro 31,4%, crédito 20,8%. Chile 2024 no publica ahorro/crédito (dash): quedan en verificación.'
);

-- ---------------------------------------------------------------------------
-- Indicadores (8 filas = 4 métricas × 2 países)
-- Regla del PRD: NO se inventan cifras. VERIFICADOS (Global Findex 2025, ronda
-- 2024, dataset oficial): Chile cuenta 85,1%; Perú cuenta 59,3%, ahorro 31,4%,
-- crédito 20,8%. La ronda 2024 no publica ahorro/crédito para Chile (dash) →
-- NULL + nota. En los comentarios va el código Findex/WDI de la métrica.
-- ---------------------------------------------------------------------------
with s as (select id from public.indicator_sources where source_key = 'global-findex-2025')
insert into public.indicators (indicator_key, country_id, source_id, value, year, fnd_code) values
    -- Chile (country_id 1)
    ('account_ownership',        1, (select id from s), 85.10, 2024, 'account.t.d / FX.OWN.TOTL.ZS | VERIFICADO: 85.1 (2024, Global Findex 2025, dataset oficial)'),
    ('saved_formally_last_year', 1, (select id from s), NULL, 2024, 'fin17a.17a1.d | ronda 2024 NO publica Chile (dash; último oficial 2021: 31,1). En verificación'),
    ('formal_credit_access',     1, (select id from s), NULL, 2024, 'fin22a.22a1.22g.d | ronda 2024 NO publica Chile (dash; último oficial 2021: 24,2). En verificación'),
    ('emergency_funds',          1, (select id from s), NULL, 2024, 'fin11/fin44 | no encontrado para Chile en la ronda 2024. En verificación'),
    -- Perú (country_id 2)
    ('account_ownership',        2, (select id from s), 59.30, 2024, 'account.t.d / FX.OWN.TOTL.ZS | VERIFICADO: 59.3 (2024, Global Findex 2025, dataset oficial)'),
    ('saved_formally_last_year', 2, (select id from s), 31.40, 2024, 'fin17a.17a1.d | VERIFICADO: 31.4 (2024, Global Findex 2025)'),
    ('formal_credit_access',     2, (select id from s), 20.80, 2024, 'fin22a.22a1.22g.d | VERIFICADO: 20.8 (2024, Global Findex 2025)'),
    ('emergency_funds',          2, (select id from s), NULL, 2024, 'fin11/fin44 | no encontrado para Perú en la ronda 2024. En verificación');

-- ---------------------------------------------------------------------------
-- Las 5 misiones del MVP (PRD sección 17, ítem 9) — llevan por los pasos 4–6:
-- input manual de finanzas → métricas → simulaciones.
-- required_actions = claves de evento que la app marca como hechas.
-- ---------------------------------------------------------------------------
insert into public.missions (slug, title, description, sort_order, required_actions) values
    ('mi-foto-financiera', 'Mi foto financiera',
     'Guarda tu primer snapshot del mes: ingresos, gastos y lo que tienes líquido.', 1,
     '["financial_inputs.created"]'),
    ('mi-deuda-en-claro', 'Mi deuda en claro',
     'Registra al menos una deuda para saber qué parte de tu ingreso se va en cuotas.', 2,
     '["liabilities.created"]'),
    ('mis-tres-numeros', 'Mis tres números',
     'Revisa tus tres métricas: meses de cobertura, ratio de deuda y concentración de ingreso.', 3,
     '["metrics.viewed"]'),
    ('escenario-emergencia', '¿Y si perdiera mi ingreso?',
     'Simula un escenario de pérdida de ingreso y mira cuánto aguantas.', 4,
     '["simulation_created" -> scenario perdida_ingreso]'),
    ('escenario-gastos', '¿Y si mis gastos suben?',
     'Crea una segunda simulación (gastos +X% o ingresos -X%) y compara.', 5,
     '["simulation_created" -> segundo escenario]');

commit;

-- =============================================================

-- Migracion 0003 : 0003_seed_lessons.sql

-- =============================================================

-- ============================================================================
-- MONEYA LATAM — Seed biblioteca (PRD sección 34 / ítem 8 del alcance)
-- 10 artículos ORIGINALES de MONEYA (redacción propia, inspirada en los 5 ejes
-- del PRD: margen de error, suficiente, consumo de estatus, riqueza invisible
-- y suerte/riesgo). NO reproduce texto de terceros y NO inventa cifras:
-- los consejos son cualitativos y remiten a las métricas propias de la app.
-- Fuente espejo en la app: lib/aprender/lessons.ts (debe mantenerse en paridad).
-- ============================================================================

begin;

with lecturas as (
    select * from (values
        ('que-es-margen-de-error', 'Qué es el margen de error',
         'El margen de error no es cuánto ganas, sino cuánto te sobra entre lo que entra y lo que sale cada mes. Es el espacio que te permite equivocarte sin caer.',
         $$Una de las diferencias más grandes en las finanzas personales no está en el sueldo, sino en el espacio entre lo que entra y lo que sale cada mes. Ese espacio es tu margen de error: la capacidad de absorber un golpe sin que se te caiga la vida.

Si se descompone el refrigerador, si el colegio cobra un permiso, si un mes sale más caro, qué pasa. Para la persona sin margen, cualquier imprevisto se convierte en deuda. Para la que tiene margen, es un ajuste incómodo y nada más.

En MONEYA medimos una parte de ese margen con los meses de cobertura: cuántos meses podrías sostener tus gastos esenciales con lo que tienes líquido, si tu ingreso desapareciera. Es una cifra simple, con fórmula visible, y no necesita que ganes más para mejorar: puedes bajar gastos, aumentar lo que guardas o las dos cosas.

El margen no es un capricho de conservador. Es la diferencia entre decidir con calma y decidir con miedo. Y se construye poco a poco: se trata de que cada mes te sobre algo, por pequeño que sea.$$,
         'room_for_error'::public.lesson_topic, 3),

        ('margen-para-imprevistos', 'El colchón no es un lujo, es margen',
         'Piensa el ahorro de emergencia no como un producto financiero, sino como el espacio que protege tus decisiones de los sobresaltos.',
         $$La palabra colchón suena a lujo o a excepción. En realidad es la parte más práctica de tus finanzas: dinero líquido al que puedes llegar sin vender nada, sin pedir crédito y sin esperar.

La regla mental simple es definir cuántos meses de gastos esenciales quieres tener disponibles. Ese número no es una meta mágica: es un espacio de decisión. Con cero meses, cualquier imprevisto te obliga a elegir entre deuda cara o dejar de pagar otras cosas. Con un mes, ganas aire. Con tres, la mayoría de los imprevistos del día a día dejan de ser una crisis. En tu app puedes ver tu propio número con los meses de cobertura, en lugar de perseguir un porcentaje inventado.

Parte del valor del colchón no se nota hasta que lo necesitas: no rinde intereses, no se ve en las redes y nadie te felicita. Pero hace que el resto de tus decisiones financieras sean menos urgentes y mejores.

Empieza por cualquier monto. Lo importante es que el flujo mensual sobre, y que lo que sobre no se confunda con un extra para gastar en el primer impulso.$$,
         'room_for_error'::public.lesson_topic, 3),

        ('que-es-suficiente', '¿Cuánto es suficiente?',
         'Suficiente no es una cifra universal: es una conversación honesta contigo sobre qué te alcanza para vivir bien.',
         $$Todos conocemos la pregunta de cuánto necesito para vivir tranquilo y la sensación de que la respuesta siempre es un poco más. La trampa está en tratar suficiente como una cifra que viene de afuera: el auto del compañero, el viaje del amigo, la vitrina del vecino.

Suficiente es una respuesta propia, y se construye en dos pasos. Primero, lo objetivo: cuánto necesitas cada mes para cubrir lo esencial, tus metas y un margen para imprevistos. Ese número puedes verlo con tus métricas en MONEYA, sin opiniones. Segundo, lo subjetivo: qué parte de tu vida estarías dispuesto a no aumentar para conservar libertad.

El riesgo no es querer más; es no saber cuándo parar. Cuando suficiente no está definido, el ingreso sube y el estilo de vida sube con él, y la sensación de escasez queda igual. Cuando está definido, cada ingreso extra deja de ser automáticamente un gasto extra y se vuelve una decisión.$$,
         'never_enough'::public.lesson_topic, 3),

        ('la-escalera-del-mas', 'La escalera sin techo',
         'Por qué es tan difícil sentirse satisfecho y qué ayuda a no caer en el nunca suficiente.',
         $$Hay una dinámica que se repite en casi todas las finanzas: el ingreso sube, las expectativas suben, y al final del mes vuelve a no sobrar nada. No es falta de disciplina: es que la referencia con la que medimos suficiente es móvil.

Cuando comparamos nuestro consumo con el del círculo que tenemos cerca, siempre hay alguien con más. Comparar es gratis y rápido, y por eso es la comparación favorita del cerebro. El problema es que rara vez comparamos lo que no se ve: la deuda que sostiene el auto del vecino, las cuotas detrás de la pantalla del bar.

Dos cosas ayudan. La primera es compararte con tu historia, no con la de otros: tu punto de partida, tu progreso, tu margen. La segunda es definir lo que suficiente significa para ti con números propios, como tus meses de cobertura o tu meta de ahorro, y dejar que ese número, no el vecino, marque el ritmo.

El nunca suficiente no se cura ganando más. Se cura dándole un número a suficiente.$$,
         'never_enough'::public.lesson_topic, 3),

        ('consumir-para-quien', '¿Para quién es ese auto?',
         'El consumo de estatus nos rodea en silencio. Aprende a detectarlo antes de que se convierta en cuotas.',
         $$Parte de lo que compramos no es para nosotros. Un auto más caro del necesario, el celular del año, la ropa que muestra marca: cada uno manda una señal. El problema no es comprar lo que te gusta, es pagar por la señal sin darte cuenta.

La pregunta que desnuda el consumo de estatus es simple: si nadie pudiera ver esta compra, ¿la haría igual? Si la respuesta es que no, estás comprando la mirada de otros con tu margen.

Esto no es una crítica moral: es una observación sobre cómo funciona la compra impulsiva. La señal se disfruta un instante, cuando la ven; la cuota se paga muchos meses, cuando ya nadie mira. Y el costo oculto más alto es el margen que dejas de construir: cada peso que se va en señal, no está en tu colchón ni en tu libertad futura.

En MONEYA el consejo es práctico y sin juicio: reconocer el gasto de estatus, separarlo del gasto que realmente te sirve, y preguntarte si la señal vale más que el margen que sacrifica. Casi siempre vale menos.$$,
         'status_consumption'::public.lesson_topic, 4),

        ('la-paradoja-de-menos', 'La paradoja de menos',
         'Tener menos cosas visibles puede darte más libertad real. Una idea incómoda y muy rentable.',
         $$Hay una paradoja en el dinero: lo que más se muestra suele ser lo que menos se tiene. Quien parece tenerlo todo en la vitrina, muchas veces está más endeudado que aquel que no muestra nada.

La riqueza que se ve, como autos, relojes y viajes permanentes, es cara de mantener y expone a quien la tiene. La riqueza que no se ve, dinero guardado, deudas bajas y margen para decidir, no da aplausos, pero da opciones.

Lo incómodo es que ambas se persiguen con el mismo ingreso. Si tu presupuesto va a la señal, no va al margen. Por eso el patrón de quien construye libertad no es gastar mejor en público, sino gastar menos en público y más en lo que no se nota.

No se trata de vivir mal, sino de no vivir para la foto. Cuando dejas de competir en la vitrina, el mismo sueldo alcanza para más vida y más tranquilidad. Esa es la paradoja de menos: bajar el consumo visible no se siente como pérdida, se siente como margen.$$,
         'status_consumption'::public.lesson_topic, 4),

        ('riqueza-invisible', 'La riqueza es lo que no ves',
         'Lo que tienes guardado no se ve, y por eso parece que no existe. Pero es lo más real de tus finanzas.',
         $$Hay una diferencia entre parecer rico y ser financieramente estable. Lo primero se construye hacia afuera; lo segundo se construye hacia adentro, en cuentas que nadie ve.

La riqueza que no se ve tiene tres ventajas. Una: no pide mantenimiento ni renovación, un auto caro hay que asegurarlo, cuidarlo y cambiarlo, una posición de liquidez no pide nada. Dos: no genera opiniones, nadie comenta lo bien que te va con tu margen, y eso está bien. Tres: es flexible, porque no está atada a una imagen.

El problema del dinero invisible es psicológico: como no se ve, cuesta creer que existe, y el instinto pide convertirlo en algo visible. Comprar en cuanto sobra es, en el fondo, una manera de confirmar que el dinero es real.

En MONEYA tu riqueza invisible es tan concreta como un número: tu saldo líquido, tu cobertura de meses, tu deuda bajo control. Medirla hace que deje de ser invisible para ti. Y tu relación con el dinero mejora cuando dejas de necesitar que otros la vean.$$,
         'invisible_wealth'::public.lesson_topic, 3),

        ('ahorrar-en-silencio', 'El pago silencioso',
         'Cada compra que no haces es un pago silencioso a favor de tu libertad futura. Así se siente vivirlo.',
         $$Casi todo lo que termina siendo tu patrimonio nació como una compra que decidiste no hacer. Es difícil de ver porque no deja rastro: no hay factura, no hay foto, no hay nadie aplaudiendo. Pero acumulado, es la diferencia entre llegar a fin de mes con deuda y llegar con margen.

Este es el pago silencioso: el dinero que no gastas, bien guardado, sin exhibirse. Se siente raro porque la cultura del consumo premia el rastro visible. Pero quien construye seguridad vive el proceso exactamente al revés: siente la compra cuando la hace, breve, y el ahorro cuando pasa el tiempo, crece.

Lo práctico es automatizar la parte que no depende de tu fuerza de voluntad: que el ahorro se aparte apenas entra el ingreso, antes de que el impulso lo reclame. Así el pago silencioso ocurre solo, todos los meses.

No es sacrificio heroico, es orden. Y a diferencia del gasto visible, que se olvida rápido, el ahorro silencioso se recuerda solo: cada vez que un imprevisto no te tumba, o que llega un mes en que puedes decidir con calma.$$,
         'invisible_wealth'::public.lesson_topic, 3),

        ('suerte-y-riesgo', 'Suerte y riesgo: la misma moneda',
         'Un mismo resultado puede venir de la habilidad, de la suerte o del riesgo. Aprende a no confundir los tres.',
         $$Durante años, decidir bien se confundió con acertar el resultado. Si la inversión subió, se asumió que fue buena; si bajó, que fue mala. Pero el resultado de casi cualquier decisión financiera mezcla tres cosas: tu habilidad, tu suerte y el riesgo que tomaste.

La suerte importa más de lo que nos gusta admitir. Dos personas pueden tomar la misma decisión y obtener resultados opuestos solo por el momento. Por eso copiar ciegamente a quien le fue bien, sin entender su suerte, es de las apuestas más caras.

El riesgo es la otra cara: algunos resultados buenos vienen de decisiones que, repetidas muchas veces, terminan mal. Una apuesta a una sola carta puede salir bien una vez y arruinarte a la décima.

La manera de tratarlos juntos es quitarte la presión del resultado único. En vez de evaluar una decisión por su desenlace, evalúa si, con la misma información y el mismo proceso, la tomarías de nuevo. Esa pregunta separa lo que dependía de ti de lo que dependió del azar. Y en temas de dinero, el proceso repetible vale más que un acierto de suerte.$$,
         'luck_risk'::public.lesson_topic, 4),

        ('proceso-no-resultado', 'Juzga el proceso, no el resultado',
         'Un buen resultado puede esconder una mala decisión y viceversa. Por eso te conviene fijarte en el proceso.',
         $$Existe una trampa estadística muy común: mirar solo a los ganadores. El que ganó la lotería, el amigo que apostó y salió bien, la inversión que todos elogian después de subir. Esta mirada olvida a todos los que hicieron lo mismo y perdieron. Se llama sesgo de supervivencia, y en las conversaciones de dinero está por todas partes.

La mayoría de las historias de éxito financiero que se cuentan son historias de una carta que salió bien. Copiarlas es asumir que la próxima saque la misma carta.

Qué hacer: juzgar decisiones por su proceso, no por su resultado. Antes de tomar una decisión financiera, define de antemano a qué le sirve. ¿Qué información uso? ¿Cuánto puedo perder sin que se caiga mi margen? ¿Lo repetiría cien veces? Si el proceso es sólido, un mal resultado es ruido del azar. Si el proceso es una apuesta, un buen resultado sigue siendo una apuesta.

La ventaja práctica es enorme: el proceso lo controlas, el resultado no. Y tu salud financiera, a diferencia de la lotería, se juega en muchos turnos, no en uno.$$,
         'luck_risk'::public.lesson_topic, 4)
    ) as t(slug, title, summary, body, topic, reading_minutes)
)
insert into public.lessons (slug, title, summary, body, topic, reading_minutes, published, created_at)
select
    l.slug,
    l.title,
    l.summary,
    l.body,
    l.topic,
    l.reading_minutes,
    true,
    '2026-09-24 08:00:00+00'::timestamptz + row_number() over (order by l.slug) * interval '1 minute'
from lecturas l;

commit;

-- =============================================================

-- Migracion 0004 : 0004_mission_completed_at.sql

-- =============================================================

begin;

-- completed_at automático según estado (PRD sección 16: misiones).
create or replace function public.sync_mission_completed_at()
returns trigger
language plpgsql
as $$
begin
    if new.status = 'completada' and old.status is distinct from 'completada' then
        new.completed_at := now();
    elsif new.status is distinct from 'completada' then
        new.completed_at := null;
    end if;
    return new;
end;
$$;

create trigger trg_mission_progress_completed_at
    before insert or update on public.mission_progress
    for each row execute function public.sync_mission_completed_at();

commit;


-- =============================================================

-- Migracion 0005 : 0005_owned_data_delete_privacy.sql

-- =============================================================

begin;

-- Habilitar borrado de los datos del usuario (PRD sección 13: exportar/eliminar datos desde V1).
create policy "profiles_delete_own" on public.profiles
    for delete using (auth.uid() = id);

create policy "events_delete_own" on public.events
    for delete using (auth.uid() = user_id);

commit;
