-- ============================================================================
-- MONEYA LATAM — V1 schema (PRD V2, secciones 12 y 20)
-- Alcance: MVP Chile + Perú. Solo tablas que V1 usa; nada "por si acaso".
-- Reglas no negociables aplicadas:
--   3. RLS activado tabla por tabla desde esta primera migración.
--   5. `indicators` solo acepta las 4 métricas Global Findex 2025 (enum).
--   Métrica norte (sección 18): tabla `events` para telemetría, sin valores
--      financieros en `properties` (regla 7, se aplica en la capa de app).
-- ============================================================================

begin;

-- ---------------------------------------------------------------------------
-- Tipos
-- ---------------------------------------------------------------------------
create type public.age_bucket as enum ('18_61', '62_plus');
create type public.employment_status as enum ('dependiente', 'independiente', 'mixto', 'estudiante', 'sin_empleo', 'otro');
create type public.liability_type as enum ('tarjeta', 'prestamo', 'hipoteca', 'vehiculo', 'otro');
create type public.scenario_type as enum ('ingresos_menos', 'gastos_mas', 'perdida_ingreso', 'emergencia', 'personalizado');
create type public.mission_status as enum ('no_iniciada', 'en_curso', 'completada');
create type public.lesson_topic as enum ('room_for_error', 'never_enough', 'status_consumption', 'invisible_wealth', 'luck_risk');
create type public.event_name as enum ('onboarding_completed', 'test_completed', 'profile_saved', 'simulation_created', 'mission_completed');

-- ---------------------------------------------------------------------------
-- Tablas de referencia (lectura para usuarios autenticados; escritura solo
-- vía service_role: sin policies de escritura).
-- ---------------------------------------------------------------------------
create table public.countries (
    id            smallint generated by default as identity primary key,
    code          text unique not null check (code in ('CL', 'PE')),
    name          text not null,
    currency_code text not null,
    locale        text not null
);

-- Regla 5 del PRD: la tabla `indicators` solo acepta las 4 métricas de Global
-- Findex 2025 en V1. Cualquier indicador nuevo requiere migración + ficha en
-- `indicator_sources`.
create type public.indicator_key as enum (
    'account_ownership',      -- % adultos con cuenta financiera (account.t.d / FX.OWN.TOTL.ZS)
    'saved_formally_last_year', -- % que ahorró formalmente en el último año (fin17a.17a1.d)
    'formal_credit_access',   -- % con acceso a crédito formal (fin22a.22a1.22g.d)
    'emergency_funds'         -- % que podría acceder a dinero extra en una emergencia (fin44)
);

create table public.indicator_sources (
    id           uuid primary key default gen_random_uuid(),
    source_key   text unique not null,
    name         text not null,
    institution  text not null,
    edition      text not null,
    data_year    smallint not null,
    methodology  text not null,
    url          text not null,
    accessed_at  date not null default current_date,
    notes        text
);

create table public.indicators (
    id            uuid primary key default gen_random_uuid(),
    indicator_key public.indicator_key not null,
    country_id    smallint not null references public.countries (id),
    source_id     uuid not null references public.indicator_sources (id),
    value         numeric(5,2) check (value between 0 and 100),
    unit          text not null default '%',
    year          smallint not null,
    fnd_code      text,
    unique (indicator_key, country_id, source_id)
);

create table public.missions (
    id               uuid primary key default gen_random_uuid(),
    slug             text unique not null,
    title            text not null,
    description      text not null,
    sort_order       smallint not null,
    required_actions jsonb not null default '[]'::jsonb
);

create table public.lessons (
    id              uuid primary key default gen_random_uuid(),
    slug            text unique not null,
    title           text not null,
    summary         text not null,
    body            text not null,
    topic           public.lesson_topic not null,
    reading_minutes smallint not null default 3 check (reading_minutes > 0),
    published       boolean not null default false,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Tablas del usuario
-- ---------------------------------------------------------------------------
create table public.profiles (
    id                uuid primary key references auth.users (id) on delete cascade,
    country_id        smallint not null references public.countries (id),
    -- El tramo de edad es requisito del scoring CFPB (18–61 vs 62+), sección 9 del PRD.
    age_bucket        public.age_bucket not null,
    employment_status public.employment_status not null,
    created_at        timestamptz not null default now(),
    updated_at        timestamptz not null default now()
);

-- Snapshot mensual. Corrección PRD: requiere saldo de liquidez (para "meses de
-- cobertura") e ingreso desglosado por fuente (para "concentración de ingreso").
create table public.financial_inputs (
    id                   uuid primary key default gen_random_uuid(),
    user_id              uuid not null references auth.users (id) on delete cascade,
    snapshot_month       date not null,
    income_dependiente   numeric(14,2) not null default 0 check (income_dependiente >= 0),
    income_independiente numeric(14,2) not null default 0 check (income_independiente >= 0),
    income_otros         numeric(14,2) not null default 0 check (income_otros >= 0),
    expenses_essential   numeric(14,2) not null default 0 check (expenses_essential >= 0),
    expenses_nonessential numeric(14,2) not null default 0 check (expenses_nonessential >= 0),
    liquid_balance       numeric(14,2) not null default 0 check (liquid_balance >= 0),
    created_at           timestamptz not null default now(),
    updated_at           timestamptz not null default now(),
    unique (user_id, snapshot_month),
    check (snapshot_month = (date_trunc('month', snapshot_month))::date)
);

create table public.liabilities (
    id             uuid primary key default gen_random_uuid(),
    user_id        uuid not null references auth.users (id) on delete cascade,
    name           text not null,
    type           public.liability_type not null,
    balance        numeric(14,2) not null check (balance >= 0),
    monthly_payment numeric(14,2) not null check (monthly_payment >= 0),
    annual_rate    numeric(6,2) not null default 0 check (annual_rate >= 0),
    created_at     timestamptz not null default now(),
    updated_at     timestamptz not null default now()
);

-- Respuestas crudas del cuestionario CFPB adaptado. Regla de validez: la escala
-- requiere que TODOS los ítems estén respondidos y que no se altere la redacción.
create table public.wellbeing_answers (
    id                 uuid primary key default gen_random_uuid(),
    user_id            uuid not null references auth.users (id) on delete cascade,
    answered_at        timestamptz not null default now(),
    items              jsonb not null,
    all_items_answered boolean not null default false,
    check (jsonb_typeof(items) = 'array')
);

-- Score ÚNICO validado CFPB (0–100, método IRT) + desglose DESCRIPTIVO de las
-- 4 dimensiones de la escala. Las dimensiones NO son scores psicométricos.
create table public.wellbeing_results (
    id                 uuid primary key default gen_random_uuid(),
    user_id            uuid not null references auth.users (id) on delete cascade,
    answers_id         uuid not null references public.wellbeing_answers (id) on delete cascade,
    score              smallint not null check (score between 0 and 100),
    dimension_control  smallint not null check (dimension_control between 0 and 100),
    dimension_shock    smallint not null check (dimension_shock between 0 and 100),
    dimension_goals    smallint not null check (dimension_goals between 0 and 100),
    dimension_freedom  smallint not null check (dimension_freedom between 0 and 100),
    note               text not null default 'Desglose descriptivo derivado de los ítems CFPB; no constituye un score psicométrico por dimensión.',
    created_at         timestamptz not null default now(),
    unique (answers_id)
);

-- "Qué pasa si": `params` guarda los inputs usados y `result` el cálculo
-- determinístico. Permite mostrar fórmula e inputs (regla 2 del PRD). Nunca
-- se calcula con IA.
create table public.simulations (
    id            uuid primary key default gen_random_uuid(),
    user_id       uuid not null references auth.users (id) on delete cascade,
    name          text not null,
    scenario_type public.scenario_type not null,
    params        jsonb not null,
    result        jsonb not null,
    created_at    timestamptz not null default now()
);

create table public.mission_progress (
    id          uuid primary key default gen_random_uuid(),
    user_id     uuid not null references auth.users (id) on delete cascade,
    mission_id  uuid not null references public.missions (id) on delete cascade,
    status      public.mission_status not null default 'no_iniciada',
    actions_done jsonb not null default '[]'::jsonb,
    completed_at timestamptz,
    updated_at  timestamptz not null default now(),
    unique (user_id, mission_id)
);

-- Telemetría (métrica norte, sección 18 PRD). REGLA 7: `properties` jamás
-- contiene valores financieros del usuario.
create table public.events (
    id          bigint generated by default as identity primary key,
    user_id     uuid references auth.users (id) on delete set null,
    event_name  public.event_name not null,
    properties  jsonb not null default '{}'::jsonb,
    created_at  timestamptz not null default now()
);

-- Toda modificación de datos financieros del usuario (PRD sección 12).
create table public.audit_logs (
    id          bigint generated by default as identity primary key,
    user_id     uuid not null references auth.users (id) on delete cascade,
    table_name  text not null,
    record_id   uuid not null,
    action      text not null check (action in ('INSERT', 'UPDATE', 'DELETE')),
    changed_at  timestamptz not null default now(),
    data        jsonb not null
);

-- ---------------------------------------------------------------------------
-- Triggers de apoyo
-- ---------------------------------------------------------------------------
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at := now();
    return new;
end;
$$;

create trigger trg_profiles_updated_at
    before update on public.profiles
    for each row execute function public.touch_updated_at();
create trigger trg_financial_inputs_updated_at
    before update on public.financial_inputs
    for each row execute function public.touch_updated_at();
create trigger trg_liabilities_updated_at
    before update on public.liabilities
    for each row execute function public.touch_updated_at();
create trigger trg_mission_progress_updated_at
    before update on public.mission_progress
    for each row execute function public.touch_updated_at();
create trigger trg_lessons_updated_at
    before update on public.lessons
    for each row execute function public.touch_updated_at();

-- Auditoría (security definer: el usuario no puede insertar logs falsos).
create or replace function public.audit_financial_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    acting_user uuid := auth.uid();
    record_id  uuid;
    snapshot   jsonb;
begin
    -- Sin contexto de usuario autenticado no se registra log (evita user_id inválidos).
    if acting_user is null then
        return coalesce(new, old);
    end if;
    record_id := coalesce(new.id, old.id);
    if tg_op = 'DELETE' then
        snapshot := to_jsonb(old);
    else
        snapshot := to_jsonb(new);
    end if;
    insert into public.audit_logs (user_id, table_name, record_id, action, data)
    values (acting_user, tg_table_name, record_id, tg_op::text, snapshot);
    return coalesce(new, old);
end;
$$;

create trigger trg_financial_inputs_audit
    after insert or update or delete on public.financial_inputs
    for each row execute function public.audit_financial_change();
create trigger trg_liabilities_audit
    after insert or update or delete on public.liabilities
    for each row execute function public.audit_financial_change();
create trigger trg_simulations_audit
    after insert or update or delete on public.simulations
    for each row execute function public.audit_financial_change();

-- ---------------------------------------------------------------------------
-- Row-Level Security (regla 3: tabla por tabla, desde la primera migración)
-- ---------------------------------------------------------------------------

-- Referencia: lectura para autenticados, escritura solo service_role.
alter table public.countries enable row level security;
alter table public.indicator_sources enable row level security;
alter table public.indicators enable row level security;
alter table public.missions enable row level security;
alter table public.lessons enable row level security;

create policy "countries_read_authenticated" on public.countries
    for select to authenticated using (true);
create policy "indicator_sources_read_authenticated" on public.indicator_sources
    for select to authenticated using (true);
create policy "indicators_read_authenticated" on public.indicators
    for select to authenticated using (true);
create policy "missions_read_authenticated" on public.missions
    for select to authenticated using (true);
create policy "lessons_read_authenticated" on public.lessons
    for select to authenticated using (true);

-- Datos del usuario: cada usuario solo ve/modifica sus propias filas.
alter table public.profiles enable row level security;
create policy "profiles_select_own" on public.profiles
    for select using (id = auth.uid());
create policy "profiles_insert_own" on public.profiles
    for insert with check (id = auth.uid());
create policy "profiles_update_own" on public.profiles
    for update using (id = auth.uid()) with check (id = auth.uid());

alter table public.financial_inputs enable row level security;
create policy "financial_inputs_select_own" on public.financial_inputs
    for select using (user_id = auth.uid());
create policy "financial_inputs_insert_own" on public.financial_inputs
    for insert with check (user_id = auth.uid());
create policy "financial_inputs_update_own" on public.financial_inputs
    for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "financial_inputs_delete_own" on public.financial_inputs
    for delete using (user_id = auth.uid());

alter table public.liabilities enable row level security;
create policy "liabilities_select_own" on public.liabilities
    for select using (user_id = auth.uid());
create policy "liabilities_insert_own" on public.liabilities
    for insert with check (user_id = auth.uid());
create policy "liabilities_update_own" on public.liabilities
    for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "liabilities_delete_own" on public.liabilities
    for delete using (user_id = auth.uid());

alter table public.wellbeing_answers enable row level security;
create policy "wellbeing_answers_select_own" on public.wellbeing_answers
    for select using (user_id = auth.uid());
create policy "wellbeing_answers_insert_own" on public.wellbeing_answers
    for insert with check (user_id = auth.uid());
create policy "wellbeing_answers_delete_own" on public.wellbeing_answers
    for delete using (user_id = auth.uid());

alter table public.wellbeing_results enable row level security;
create policy "wellbeing_results_select_own" on public.wellbeing_results
    for select using (user_id = auth.uid());
create policy "wellbeing_results_insert_own" on public.wellbeing_results
    for insert with check (user_id = auth.uid());
create policy "wellbeing_results_delete_own" on public.wellbeing_results
    for delete using (user_id = auth.uid());

alter table public.simulations enable row level security;
create policy "simulations_select_own" on public.simulations
    for select using (user_id = auth.uid());
create policy "simulations_insert_own" on public.simulations
    for insert with check (user_id = auth.uid());
create policy "simulations_update_own" on public.simulations
    for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "simulations_delete_own" on public.simulations
    for delete using (user_id = auth.uid());

alter table public.mission_progress enable row level security;
create policy "mission_progress_select_own" on public.mission_progress
    for select using (user_id = auth.uid());
create policy "mission_progress_insert_own" on public.mission_progress
    for insert with check (user_id = auth.uid());
create policy "mission_progress_update_own" on public.mission_progress
    for update using (user_id = auth.uid()) with check (user_id = auth.uid());

alter table public.events enable row level security;
create policy "events_insert_own" on public.events
    for insert with check (user_id = auth.uid());
create policy "events_select_own" on public.events
    for select using (user_id = auth.uid());

-- Sin policies de insert/update/delete: los logs solo los escribe el trigger
-- security definer. El usuario puede leer y, para borrado (derecho al olvido),
-- eliminar sus propias filas.
alter table public.audit_logs enable row level security;
create policy "audit_logs_select_own" on public.audit_logs
    for select using (user_id = auth.uid());
create policy "audit_logs_delete_own" on public.audit_logs
    for delete using (user_id = auth.uid());

-- ---------------------------------------------------------------------------
-- Índices de uso frecuente
-- ---------------------------------------------------------------------------
create index idx_financial_inputs_user_month on public.financial_inputs (user_id, snapshot_month);
create index idx_liabilities_user on public.liabilities (user_id);
create index idx_wellbeing_results_user on public.wellbeing_results (user_id);
create index idx_simulations_user on public.simulations (user_id);
create index idx_mission_progress_user on public.mission_progress (user_id);
create index idx_events_user_created on public.events (user_id, created_at);
create index idx_audit_logs_user on public.audit_logs (user_id, changed_at);
create index idx_indicators_country_key on public.indicators (country_id, indicator_key);

commit;